version = 0.1

[default.deploy.parameters]
stack_name = "api-movil"
resolve_s3 = true
s3_prefix = "api-movil"
region = "eu-central-1"
profile = "insyte"
confirm_changeset = true
tags = "proyecto=fotosobra-api"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-central-1"
